# Generated by Django 5.0.1 on 2024-06-06 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddRoommate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'AddRoommate',
            },
        ),
        migrations.CreateModel(
            name='PUBBillAmount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pre_date', models.DateField(null=True)),
                ('prev_read', models.FloatField(default=0)),
                ('cur_date', models.DateField(null=True)),
                ('cur_read', models.FloatField(default=0)),
                ('total_units', models.FloatField(default=0)),
                ('refuse_amt', models.FloatField(default=0)),
                ('water_amt', models.FloatField(default=0)),
                ('gst', models.FloatField(default=0)),
                ('total_amt', models.FloatField(default=0, null=True)),
                ('food_date', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'PUBBillAmount',
            },
        ),
        migrations.CreateModel(
            name='AddExpense',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('item_price', models.FloatField()),
                ('date', models.DateField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.addroommate')),
            ],
            options={
                'db_table': 'AddExpense',
            },
        ),
        migrations.CreateModel(
            name='ExpensePaidAmount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('month_year', models.CharField(max_length=50)),
                ('no_of_days', models.IntegerField(null=True)),
                ('food_expense', models.FloatField()),
                ('total_paid_pub', models.FloatField(default=0, null=True)),
                ('pub', models.FloatField(default=0, null=True)),
                ('balance', models.FloatField(default=0, null=True)),
                ('purchase', models.FloatField(default=0, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.addroommate')),
            ],
            options={
                'db_table': 'ExpensePaidAmount',
            },
        ),
    ]
