# Generated by Django 5.0.4 on 2024-05-22 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensePaidAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(max_length=50)),
                ('no_of_days', models.IntegerField(null=True)),
                ('food_expense', models.FloatField()),
                ('total_paid_pub', models.FloatField(default=0, null=True)),
                ('pub', models.FloatField(default=0, null=True)),
                ('balance', models.FloatField(default=0, null=True)),
                ('purchase', models.FloatField(default=0, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.addroommate')),
            ],
        ),
    ]
