# Generated by Django 5.0.4 on 2024-05-23 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_pubbillamount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pubbillamount',
            old_name='total_units',
            new_name='unit_cost',
        ),
    ]
