# Generated by Django 5.0.4 on 2024-05-23 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_rename_total_units_pubbillamount_unit_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pubbillamount',
            old_name='unit_cost',
            new_name='total_units',
        ),
    ]
