# Generated by Django 5.0.1 on 2024-05-31 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_rename_unit_cost_pubbillamount_total_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='addroommate',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='addexpense',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='addroommate',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='expensepaidamount',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pubbillamount',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='addexpense',
            table='AddExpense',
        ),
        migrations.AlterModelTable(
            name='addroommate',
            table='AddRoommate',
        ),
        migrations.AlterModelTable(
            name='expensepaidamount',
            table='ExpensePaidAmount',
        ),
        migrations.AlterModelTable(
            name='pubbillamount',
            table='PUBBillAmount',
        ),
    ]
